title: Sample Github page
author: Duong Do 
email: your-email@domain.com
description: Welcome to Gihub page tutorial with Duong Do

# social links
github_username:  duongdo27

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
